#!/usr/bin/env php
<?php
/**
 * Combine Listening Test 8 Section 1 and Section 2 into one XML file
 */

if (php_sapi_name() !== 'cli') {
    die("This script must be run from the command line.\n");
}

function extractQuestionsFromXML($xmlContent) {
    if (preg_match('/<wp:meta_key><!\[CDATA\[_ielts_cm_questions\]\]><\/wp:meta_key>\s*<wp:meta_value><!\[CDATA\[(.*?)\]\]><\/wp:meta_value>/s', $xmlContent, $match)) {
        $serialized = $match[1];
        $data = @unserialize($serialized);
        if ($data !== false) {
            return $data;
        }
    }
    return [];
}

function extractMetaValue($xmlContent, $metaKey) {
    $pattern = '/<wp:meta_key><!\[CDATA\[' . preg_quote($metaKey, '/') . '\]\]><\/wp:meta_key>\s*<wp:meta_value><!\[CDATA\[(.*?)\]\]><\/wp:meta_value>/s';
    if (preg_match($pattern, $xmlContent, $match)) {
        return $match[1];
    }
    return "";
}

// Section files
$sections = [
    __DIR__ . "/Listening Test 8 Section 1.xml",
    __DIR__ . "/Listening Test 8 Section 2.xml",
];

$allQuestions = [];
$allTranscripts = [];
$audioUrl = "";

echo "Combining Listening Test 8 Section 1 and 2...\n";

foreach ($sections as $i => $file) {
    $sectionNum = $i + 1;
    echo "Processing Section $sectionNum... ";
    
    if (!file_exists($file)) {
        echo "NOT FOUND\n";
        die("Error: File not found: $file\n");
    }
    
    $content = file_get_contents($file);
    $questions = extractQuestionsFromXML($content);
    
    if (!empty($questions)) {
        $allQuestions = array_merge($allQuestions, array_values($questions));
        echo count($questions) . " questions\n";
    } else {
        echo "NO QUESTIONS\n";
    }
    
    // Extract transcript
    $transcript = extractMetaValue($content, '_ielts_cm_transcript');
    if ($transcript) {
        $allTranscripts[] = $transcript;
    }
    
    // Get audio URL from first section
    if ($i === 0) {
        $audioUrl = extractMetaValue($content, '_ielts_cm_audio_url');
    }
}

// Reindex from 0
$reindexed = array_values($allQuestions);

echo "\nTotal questions: " . count($reindexed) . "\n";

if (count($reindexed) === 0) {
    die("Error: No questions found in sections!\n");
}

// Serialize the questions array
$serialized = serialize($reindexed);
$combinedTranscript = implode("\n\n<hr />\n\n", $allTranscripts);

// Create XML with proper structure
$xml = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<!--  This is a WordPress eXtended RSS file for IELTS Course Manager exercise export  -->
<!--  Generated by generate-test-8-section-1-and-2.php on {DATE}  -->
<rss xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:wp="http://wordpress.org/export/1.2/" version="2.0">
<channel>
<title>IELTStestONLINE</title>
<link>https://www.ieltstestonline.com/2026</link>
<description>Online IELTS preparation</description>
<pubDate>{PUBDATE}</pubDate>
<language>en-NZ</language>
<wp:wxr_version>1.2</wp:wxr_version>
<wp:base_site_url>https://www.ieltstestonline.com/2026</wp:base_site_url>
<wp:base_blog_url>https://www.ieltstestonline.com/2026</wp:base_blog_url>
<wp:author>
<wp:author_id>1</wp:author_id>
<wp:author_login><![CDATA[impact]]></wp:author_login>
<wp:author_email><![CDATA[impact@ieltstestonline.com]]></wp:author_email>
<wp:author_display_name><![CDATA[impact]]></wp:author_display_name>
<wp:author_first_name><![CDATA[Patrick]]></wp:author_first_name>
<wp:author_last_name><![CDATA[Bourne]]></wp:author_last_name>
</wp:author>
<generator>IELTS Course Manager</generator>
<item>
<title><![CDATA[Listening Test 8 - Sections 1 and 2 (Questions 1-20)]]></title>
<link>https://www.ieltstestonline.com/2026/ielts-quiz/listening-test-8-section-1-and-2/</link>
<pubDate>{PUBDATE}</pubDate>
<dc:creator><![CDATA[impact]]></dc:creator>
<guid isPermaLink="false">https://www.ieltstestonline.com/2026/?post_type=ielts_quiz&amp;p=AUTO</guid>
<description/>
<content:encoded><![CDATA[]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>AUTO</wp:post_id>
<wp:post_date><![CDATA[{POSTDATE}]]></wp:post_date>
<wp:post_date_gmt><![CDATA[{POSTDATE_GMT}]]></wp:post_date_gmt>
<wp:post_modified><![CDATA[{POSTDATE}]]></wp:post_modified>
<wp:post_modified_gmt><![CDATA[{POSTDATE_GMT}]]></wp:post_modified_gmt>
<wp:comment_status><![CDATA[closed]]></wp:comment_status>
<wp:ping_status><![CDATA[closed]]></wp:ping_status>
<wp:post_name><![CDATA[listening-test-8-section-1-and-2]]></wp:post_name>
<wp:status><![CDATA[publish]]></wp:status>
<wp:post_parent>0</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type><![CDATA[ielts_quiz]]></wp:post_type>
<wp:post_password><![CDATA[]]></wp:post_password>
<wp:is_sticky>0</wp:is_sticky>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_questions]]></wp:meta_key>
<wp:meta_value><![CDATA[$serialized]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_reading_texts]]></wp:meta_key>
<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_pass_percentage]]></wp:meta_key>
<wp:meta_value><![CDATA[70]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_layout_type]]></wp:meta_key>
<wp:meta_value><![CDATA[listening_practice]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_exercise_label]]></wp:meta_key>
<wp:meta_value><![CDATA[practice_test]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_open_as_popup]]></wp:meta_key>
<wp:meta_value><![CDATA[]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_scoring_type]]></wp:meta_key>
<wp:meta_value><![CDATA[ielts_listening]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_timer_minutes]]></wp:meta_key>
<wp:meta_value><![CDATA[]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_starting_question_number]]></wp:meta_key>
<wp:meta_value><![CDATA[1]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_audio_url]]></wp:meta_key>
<wp:meta_value><![CDATA[$audioUrl]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_transcript]]></wp:meta_key>
<wp:meta_value><![CDATA[$combinedTranscript]]></wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key><![CDATA[_ielts_cm_audio_sections]]></wp:meta_key>
<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
</wp:postmeta>
</item>
</channel>
</rss>
XML;

// Replace date placeholders
$now = time();
$pubDate = gmdate('D, d M Y H:i:s', $now) . ' +0000';
$postDate = gmdate('Y-m-d H:i:s', $now);
$postDateGmt = gmdate('Y-m-d H:i:s', $now);
$generatedDate = gmdate('Y-m-d H:i:s', $now);

$xml = str_replace('{DATE}', $generatedDate, $xml);
$xml = str_replace('{PUBDATE}', $pubDate, $xml);
$xml = str_replace('{POSTDATE}', $postDate, $xml);
$xml = str_replace('{POSTDATE_GMT}', $postDateGmt, $xml);

$outputFile = __DIR__ . "/Listening-Test-8-Section-1-and-2.xml";
file_put_contents($outputFile, $xml);

echo "\n✓ Combined XML written to: $outputFile\n";
echo "  Questions: " . count($reindexed) . "\n";
echo "  Audio URL: " . ($audioUrl ? $audioUrl : "(none)") . "\n";
